### ISSUE TITLE
Huge bug when trying to refersh (F3+T)

### ISSUE THREAD

**Issue by red2blue** [Keksuccino/Drippy-Loading-Screen#2]
1.17.1
Latest Drippy ver

--

When playing the game and trying to refresh via f3 + t or adding/changing resource pack, the game locks up and gets stuck in a loop, does not crash, but loops. 

I'd post the latest.log but its 200mb long.

Looking at the latest.log, its cycling through this message 

    at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52) ~[?:?]
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:870) ~[?:?]
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112) ~[?:?]
    at net.minecraft.client.MinecraftClient.reset(MinecraftClient:2233) ~[?:?]
    at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2203) ~[?:?]
    at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.resetGameState(InGameCatcher.java:104) ~[notenoughcrashes-3.3.1+1.17-fabric.jar:?]
    at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:32) ~[notenoughcrashes-3.3.1+1.17-fabric.jar:?]
    at net.minecraft.client.MinecraftClient.modify$cej000$onCrash(MinecraftClient:13599) ~[?:?]
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:752) ~[?:?]
    at net.minecraft.client.MinecraftClient.handler$cej000$afterCrashHandled(MinecraftClient:13591) ~[?:?]
    
----

    and then after that  it does this over and over and over again
    
----

        at net.minecraft.client.MinecraftClient.handler$cej000$afterCrashHandled(MinecraftClient:13591) ~[?:?]
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:752) ~[?:?]
    ----

    Finally, whenever you end task via task manager and open latest log, there is a part that ends this loop before it goes back into it.
    ----
    
    	at net.minecraft.client.MinecraftClient.handler$cej000$afterCrashHandled(MinecraftClient:13591) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.lang.IllegalArgumentException: Color parameter outside of expected range: Alpha
	at java.awt.Color.testColorValueRange(Color.java:310) ~[?:?]
	at java.awt.Color.<init>(Color.java:395) ~[?:?]
	at de.keksuccino.drippyloadingscreen.customization.items.SplashTextCustomizationItem.renderSplash(SplashTextCustomizationItem.java:189) ~[drippyloadingscreen_fabric_1.1.0-2_MC_1.17-1.17.1.jar:?]
	at de.keksuccino.drippyloadingscreen.customization.items.SplashTextCustomizationItem.render(SplashTextCustomizationItem.java:122) ~[drippyloadingscreen_fabric_1.1.0-2_MC_1.17-1.17.1.jar:?]
	at de.keksuccino.drippyloadingscreen.customization.rendering.splash.SplashCustomizationLayer.renderLayer(SplashCustomizationLayer.java:153) ~[drippyloadingscreen_fabric_1.1.0-2_MC_1.17-1.17.1.jar:?]
	at net.minecraft.client.gui.screen.SplashOverlay.handler$dnp002$onRender(SplashOverlay:616) ~[?:?]
	at net.minecraft.client.gui.screen.SplashOverlay.render(SplashOverlay) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:863) ~[?:?]
	... 871 more
[23:37:14] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[23:37:14] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[23:37:14] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: null
[23:37:14] [Render thread/FATAL]: Minecraft ran into a problem! Report saved to: D:\minecraftmods\Instances\Another Quality Modpack 2 (1)\crash-reports\crash-2021-09-05_23.37.14-client.txt
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 9/5/21, 11:37 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error

**Comment by Keksuccino** [comment]
Thank you for telling me! This bug is fixed now with the release of Drippy Loading Screen v1.1.1!
