### ISSUE TITLE
NullPointer crash on start

### ISSUE THREAD

**Issue by Keksuccino** [Keksuccino/Drippy-Loading-Screen#25]
- https://discord.com/channels/704163135787106365/1063259946403250226/1063259946403250226

```
Exception message: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.Map.get(Object)" is null
Stacktrace:
	at de.keksuccino.konkrete.PostLoadingHandler.addEvent(PostLoadingHandler.java:28) ~[konkrete_forge_1.6.0_MC_1.18-1.18.2.jar%23163!/:1.0.0] {re:classloading}
	at de.keksuccino.konkrete.Konkrete.addPostLoadingEvent(Konkrete.java:99) ~[konkrete_forge_1.6.0_MC_1.18-1.18.2.jar%23163!/:1.0.0] {re:classloading}
	at de.keksuccino.drippyloadingscreen.DrippyLoadingScreen.<init>(DrippyLoadingScreen.java:85) ~[drippyloadingscreen_forge_1.6.6_MC_1.18-1.18.2.jar%23114!/:1.0.0] {re:mixin,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {re:mixin}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.0.jar%23243!/:?] {}
```

**Comment by Keksuccino** [comment]
Closed because full rewrite of mod.
